name: e_wallet
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Magnes <smb909@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  sass_builder: ^2.1.2
  intl: ^0.15.8